// Auto-generated by make — do not edit
let buildVersion = "0.6.22"
let buildCommit = "b869e20"
let buildBranch = "main"
let buildDate = "2026-04-03 12:35:57 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
