// Auto-generated by make — do not edit
let buildVersion = "0.7.7"
let buildCommit = "d09fd82"
let buildBranch = "main"
let buildDate = "2026-04-04 20:59:16 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
